name: first-workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ububtu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: "bye bye"
